module.exports = {
  authController: require('./authController'),
  cronController: require('./cronController'),
  mailController: require('./mailController'),
  userController: require('./userController'),
  medicineController: require('./medicineController'),
  batchController: require('./batchController'),
  importOrderController: require('./importOrderController'),
  locationController: require('./locationController'),
  notificationController: require('./notificationController'),
  thingsboardController: require('./thingsboardController'),
  ImportInspectionController: require("./importInspectionController"),
  packageController: require('./packageController'),
  areaController: require('./areaController'),
};
